CREATE TABLE Equipment
(
    ID INT NOT NULL PRIMARY KEY UNIQUE,
    Name VARCHAR(50) NOT NULL,
    Price INT NOT NULL
);
CREATE TABLE TV_Shows
(
    ID INT NOT NULL PRIMARY KEY UNIQUE,
    TV_Shows INT NOT NULL UNIQUE,
    GenreID INT NOT NULL,
    Description VARCHAR(100) NOT NULL,
    FOREIGN KEY (GenreID)
        REFERENCES TV_Shows_Genre(ID)
        ON DELETE CASCADE ON UPDATE NO ACTION
);
CREATE TABLE Job_Title
(
    ID INT NOT NULL PRIMARY KEY UNIQUE,
    Job_Title VARCHAR(50) NOT NULL,
    Salary INT NOT NULL UNIQUE
);

CREATE TABLE Department
(
    ID INT NOT NULL PRIMARY KEY UNIQUE,
    Name VARCHAR(50) NOT NULL

);

CREATE TABLE TV_Shows_Genre
(
    ID INT NOT NULL PRIMARY KEY UNIQUE,
    Genre VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE Specialization
(
    ID INT NOT NULL PRIMARY KEY UNIQUE,
    Specialization VARCHAR(50) NOT NULL

);

CREATE TABLE Invited
(
    ID INT NOT NULL PRIMARY KEY UNIQUE,
    Full_Name VARCHAR(50) UNIQUE NOT NULL,
    Arrival_Date DATE NOT NULL
);

CREATE TABLE posts(
    id INTEGER PRIMARY KEY UNIQUE,
    name VARCHAR(100)
);

CREATE TABLE Tv_Program_Guide
(
    ID INT NOT NULL PRIMARY KEY UNIQUE,
    Employees VARCHAR(50) NOT NULL UNIQUE,
    Data DATE NOT NULL,
    Start_Time TIME NOT NULL,
    End_Time TIME NOT NULL,
    TV_ShowsID INT NOT NULL UNIQUE,
    TV_ChannelID int NOT NULL UNIQUE,
    FOREIGN KEY (TV_ShowsID)
        REFERENCES TV_Shows(ID)
        ON DELETE CASCADE ON UPDATE NO ACTION,
    FOREIGN KEY (TV_ChannelID)
        REFERENCES TV_Channel(ID)
        ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE Employees
(
    ID INT NOT NULL PRIMARY KEY UNIQUE,
    Full_Name VARCHAR(50) NOT NULL,
    Job_TitleID INT NOT NULL,
    Phone INT NOT NULL UNIQUE,
    Address VARCHAR(100) NOT NULL UNIQUE,
    Schedule DATETIME NOT NULL UNIQUE,
    DepartmentID INT NOT NULL UNIQUE,
    EquipmentID INT NOT NULL UNIQUE,
    FOREIGN KEY (Job_TitleID)
        REFERENCES Job_Title(ID)
        ON DELETE CASCADE ON UPDATE NO ACTION,
    FOREIGN KEY (DepartmentID)
        REFERENCES Department(ID)
        ON DELETE CASCADE ON UPDATE NO ACTION,
    FOREIGN KEY (EquipmentID)
        REFERENCES Equipment(ID)
        ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE TV_Channels
(
    ID INT NOT NULL PRIMARY KEY UNIQUE,
    TV_Channel INT NOT NULL,
    InvitedID INT NOT NULL,
    SpecializationID INT NOT NULL UNIQUE,
    FOREIGN KEY (InvitedID)
        REFERENCES Invited(ID)
        ON DELETE CASCADE ON UPDATE NO ACTION,
    FOREIGN KEY (SpecializationID)
        REFERENCES Specialization(ID)
        ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE TV_Shows
(
    ID INT NOT NULL PRIMARY KEY UNIQUE,
    TV_Shows INT NOT NULL UNIQUE,
    GenreID INT NOT NULL,
    Description VARCHAR(100) NOT NULL,
    FOREIGN KEY (GenreID)
        REFERENCES TV_Shows_Genre(ID)
        ON DELETE CASCADE ON UPDATE NO ACTION
);

